apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: affine-doc
  description: Affine documentation service
  annotations:
    backstage.io/managed-by-location: url:https://github.com/DevOps-Fusion/AFFine-Docs-code/catalog-info.yaml
    jenkins.io/job-name: "Affine-doc"
spec:
  type: service
  lifecycle: production
  owner: DevOps-Fusion
  repository: https://github.com/DevOps-Fusion/AFFine-Docs-code
  system: devops-fusion-system
  links:
    - url: http://54.242.131.80:8080/job/Affine-doc/
      title: Jenkins Pipeline
    - url: https://100.24.37.22:30138/namespace/devopstask/workloads
      title: Kubernetes Deployment
